name: .NET Core

on:
  push:
    branches:
      - main
      - release/*
      - feature/*
  pull_request:
    branches:
      - main
      - release/*
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    # - name: Run tests
    #  run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack
