name: .NET Core

on:
  push:
    branches:
      - main
      - release/*
      - feature/*
  pull_request:
    branches:
      - main
      - release/*
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Determine Version
      id: version
      run: |
        MAJOR=1
        MINOR=0
        PATCH=2
        if [[ $GITHUB_REF == refs/heads/feature/* ]]; then
          VERSION="${MAJOR}.${MINOR}.${PATCH}-feature.${GITHUB_RUN_ID}"
        elif [[ $GITHUB_REF == refs/heads/main ]]; then
          VERSION="${MAJOR}.${MINOR}.${PATCH}-main.${GITHUB_RUN_ID}"
        elif [[ $GITHUB_REF == refs/heads/release/* ]]; then
          VERSION="${MAJOR}.${MINOR}.${PATCH}"
        else
          VERSION="${MAJOR}.${MINOR}.${PATCH}-anotherbranch.${GITHUB_RUN_ID}"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        
    - name: Pack
      run: dotnet pack --no-build --output ./nupkg /p:PackageVersion=${{ env.VERSION }}
      
    - name: Publish to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
